[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirect API requests to our Netlify function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/data.js/:splat"
  status = 200